language: python
python: 3.8
install: pip install -r requirements.txt


deploy:
  provider  : heroku
  api_key   : $HEROKU_API_KEY
  app       : ankurblogcode
  run       : python manage.py migrate
  on        : master